### ISSUE TITLE
How can I add more tokens to my reward mint?

### ISSUE THREAD

**Issue by Giswin** [gemworks/gem-farm#107]
I am new to blockchain, I hope this quesion won't be too silly to you.

I created a farm and created Reward Mint A, it creates 1 million tokens by default.

If I need more tokens, how can I add more tokens to mint A?

**Comment by numisman** [comment]
watching this.  Not sure if you have to just fund it with more tokens or if you have to reset the farm by cancelling the current funding and resetting the earning rate.  Would love a clear answer here.

**Comment by Giswin** [comment]
Funding  more tokens to Reaward A without changing anything else is what I try to do. Thanks

**Comment by numisman** [comment]
Yep - that should do it.  Let us know if it worked for you.

**Comment by Giswin** [comment]
this is the error when I funder Reward A with more tokens:

![image](https://user-images.githubusercontent.com/2694092/174455124-c2a115a7-6cd2-4e9a-9ea9-1b21f53d2e3b.png)

I am using the wallet which was used to create the farm,
which was added as the Authorized funder 
My wallet has 4 SOL

**Comment by numisman** [comment]
Are you funding the farm in SOL?

0x1 means insufficient funds, but those funds are likely the token you actually want to reward your users with.  If you have enough in there for that, then I'm not sure what it might be.

At any rate, you'll need some SOL (which you have) for the txn, and then you'll have the amount that you need to fund your reward.

**Comment by Giswin** [comment]
this is what i am trying to do: 
![image](https://user-images.githubusercontent.com/2694092/174456410-77050d7a-b14f-45ae-a8c8-0705ec9d30ee.png)

Ijust want Reward A has more tokens for me to reward people.
When I created the farm, I reated 2 rewards mints, each has 1 million tokens as default, I funded the 1 million tokens.
After I want to have another 1 millon token for my Reward A.

**Comment by numisman** [comment]
True, but once you get it, you get it.

So unfortunately you won't be able to get more tokens because the program owns the right to mint more of those (unless @Ilmoi transferred the right to mint to your wallet when he created the token). 

I think he gave us the test mints just as a way of testing things out and not to actually use.  In your position, I would create a new token to use that you have the full authority for.  The information you need to do that is in the solana command line application.

In addition, you can have a look at a video here that shows you how to create your own token:  https://www.youtube.com/watch?v=SNcLCM47VR4&t=314s

Andy's videos are solid.  That link takes you to the spot in the video where he explains how to create a token for the Candy Machine (the standard NFT platform in Solana), but it will work for this as well.

You can create whatever supply you want when you have the token mint, and then you can increase it by minting more or decrease it by burning it.  But once you have the mint id, you would just use that here in the staking farm for the Reward mint.

Hope that helps!

**Comment by Giswin** [comment]
Thank you so so much @numisman, it worked out for me.

**Comment by numisman** [comment]
I'm so glad!  Congrats!
