### ISSUE TITLE
Completely new farm created - new staker not accruing tokens

### ISSUE THREAD

**Issue by numisman** [gemworks/gem-farm#110]
OK - I rewatched the video to ensure I was doing it right.

I am rewarding a 6 decimal token, and I want to reward 800 total tokens per day.
So I set the base rate at 800,000,000 (800 tokens for a 6 decimal mint), and set the duration for 300 (to test for 5 minutes).
I set the denominator to 86400 (the total number of seconds in a day)
The rest of the levels were set to 0.
I funded the bank with 677440000000000 (total number of tokens to allow staking for all users for all tokens * 1000000(6 decimal mint)
I set the time frame to 300 (5 minutes) to make sure that I can stake properly.
I would expect to be gaining 0.009253 tokens per second.  I am receiving none.

HOW DO I GET THIS APP TO WORK?  WHAT AM I DOING WRONG?  @ilmoi OR ANYONE PLEASE ANSWER MY ISSUES PLEASE!  MY COMMUNITY IS WAITING FOR THIS TO BE ABLE TO EARN TOKENS.

This is the farmer status - you can see I have 1 gem staked: 
![image](https://user-images.githubusercontent.com/87335441/174423947-18ca5a35-e657-49a4-829b-d9f43859ebd9.png)

This is the farm config:
![image](https://user-images.githubusercontent.com/87335441/174423991-6d9909ec-1163-43ea-ac5a-8aebadb35d70.png)
WHAT AM I MISSING?

Thanks in advance!

**Comment by ilmoi** [comment]
Just went and tested new farm creation + staking from scratch on mainnet, everything works as intended. 
<img width="504" alt="image" src="https://user-images.githubusercontent.com/10000242/174443312-bfb841ba-8774-4625-a2e8-3f94114ff559.png">

The fact that your "reserved amount" is set to 0 is worrying - this means the farm hasn't allocated any tokens to the new farmer. 

Possible causes:

Did you have a previous schedule that the farmer was enrolled in? If yes then until that schedule completes new one won't kick in. Goes like this:
- you had a previous schedule going eg until 20th june with 0 tokens rate
- you enrolled the farmer there
- then you started a new schedule with actual rewards
- but until old one completes, farmer can't be re-enrolled

Other ideas:
- did you try setting duration for longer than 5 min? You need to enroll before schedule completes, maybe you're too late
- did you try hitting "refresh farmer"?
- did you try claiming rewards? Maybe it's a UI bug but onchain code works as expected

**Comment by numisman** [comment]
First off - THANK YOU for the effort in looking into this @ilmoi.  I truly appreciate it.

Secondly - I created a farm and funded it with 677440000000000 originally.  Then I updated the duration but didn't add any additional funding.  I also did try setting the duration for 30 minutes to see if that would help and I definitely clicked refresh, but it still did not accrue any new tokens.

Is there a way to end the clock early?  I thought that was done through withdrawing, but is it actually done by unstaking and restaking?  Or, is it done simply by refreshing farmer?

Can you also validate that it's just not accruing at too small a rate to be noticed?  The formula I'm using is (800 tokens per day * 1000000 for decimals in token) / (86400 seconds in a day)

When I tested the functionality it was using the built app at https://www.gemfarm.gg/farmer, so assuming that is using your latest version of the code, then I would assume I'm using it correctly....but I don't see how I can "kick in" the earning.

I will do a git clone fresh from scratch, build the UI and test with that.  But our skin is really just CSS built on top of your functionality and none of the calls to the on-chain program are modified.  

And also - a curiosity - what does "Min staking ends" mean here?  It looks like it's the same as the time that Staking begins for the farmer.

![image](https://user-images.githubusercontent.com/87335441/174449860-e8d1db32-e75c-4bae-9c11-dcb3a031e168.png)

Thanks again for the attention!

**Comment by ilmoi** [comment]
Okkkkkkkkkkkkk I know what the problem is

here I've replicated your numbers 1:1 and it all works:
![image](https://user-images.githubusercontent.com/10000242/174451534-ed7ea1ff-f13c-48a3-a677-c10a036f92ec.png)

![image](https://user-images.githubusercontent.com/10000242/174451551-56c7b7d1-0477-40ab-8922-e35aba66de19.png)

the issue is: 
- you've correctly set the base rate to 800,000,000
- but base rate only lasts UNTIL T1 kick in, which in your case is 0 seconds
- at which point you're gonna be paying out T1 rate which is 0 tokens
- so at 0 seconds you start paying out 0 tokens, which is why total paid out reward is 0

here's what you do:
- cancel existing reward & withdraw funding.
- don't put 0s into T1, T2 etc - just leave them empty. Only put numbers into base rate and denominator, like this:
- start a new reward, re-enroll the farmer
![image](https://user-images.githubusercontent.com/10000242/174451619-1f51c314-0626-4b42-bb31-f4803254020b.png)

one thing to remember - if your current farmer is staked until time X (eg 20th jun), you can't re-enroll them in a new reward until either 1)that date passes or 2)they unstake themselves. So be sure to unstake and restake - this will enroll them in new reward.

hope helps.

**Comment by numisman** [comment]
OMG if this does it I will love you forever.  Platonically, but forever.  Also if you'd like to see our UI you're welcome to see it at https://stake.imsogame.com/farmer.

**Comment by numisman** [comment]
OH THANK GOODNESS!!!
![image](https://user-images.githubusercontent.com/87335441/174451998-7aaae84d-67e2-4954-85a9-e5157a5fd0c5.png)
This was a week of pain for me.  Not sure why I thought I needed the zeroes in there, but removing them did the trick.  THANK YOU SO MUCH!!!  My community is going to be so happy!  Now to retract my tweet publicly asking for forgiveness!
Thanks @ilmoi.  You're a beast!  If you want a Chimp to try out our UI I'd be happy to provide it - DM me a wallet on twitter if you'd like.  But don't do so UNTIL I FIX THESE NUMBERS!

**Comment by numisman** [comment]
Oh and also - THIS IS THE SOLUTION so I'm closing the issue.  Thanks again!
